### ISSUE TITLE
Getting on GitHub

### ISSUE THREAD

**Issue by bumpersp** [mkleinha/sqlite_interface#2]
@mkleinha  @knconnelly . I have cloned the repo Max made and created a Version Control project on my local desktop so that I can push/pull from the Repo. Kyle confirm when you have done so. I'm also testing this Issue tool as a means of communication.

**Comment by knconnelly** [comment]
This works.  I made the ui branch and was going to tackle my edits that way, then push (is that right?) to the master every time I successfully add a feature.

**Comment by bumpersp** [comment]
i think that makes sense-everything we do should be branched-which I screwed up the first time. 
Should someone review the branch edits before accepting a push to the master? @mkleinha
